#!/usr/bin/bash
termux-setup-storage
apt update -y
apt upgrade -y
apt dist-upgrade -y
pkg install game-repo -y
apt install root-repo -y
apt install x11-repo -y
apt install termux-api -y
pkg install science-repo -y
apt install git -y
apt install wget -y
aot install curl -y
apt install fish -y
curl -LO https://its-pointless.github.io/setup-pointless-repo.sh
bash setup-pointless-repo.sh
pkg autoclean
pkg clean
termux-change-repo
